remote_theme: piksel/ghtheme-piksel
minimal_mistakes_skin: piksel
repository: piksel/piksel.github.io
title: dev.p1k.se
search: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/pikselbitworks
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/piksel
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: https://gitlab.com/p1ksel
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: https://bitbucket.org/p1ksel
